-- Generated by scripts/process-nodeine-moon-import.mjs from the reviewed manifest.
-- Additive content only. No schema, grants, auth, messages or existing worlds changed.
-- Publish the matching web assets first. Reruns do not overwrite owner edits.
begin;
do $$ begin
  if not exists (select 1 from public.profiles where id='75df596f-cfa3-42ce-a335-a3580ce6172b') then raise exception 'Expected owner is missing'; end if;
  if exists (select 1 from public.collections where (slug='aspects-of-the-moon' and id<>'8ef7fee8-f4a8-54c1-b91a-9be2d32184f5') or (id='8ef7fee8-f4a8-54c1-b91a-9be2d32184f5' and owner_id<>'75df596f-cfa3-42ce-a335-a3580ce6172b')) then raise exception 'World identity collision'; end if;
end $$;
insert into public.collections (id,owner_id,title,slug,summary,world_code,sort_order)
values ('8ef7fee8-f4a8-54c1-b91a-9be2d32184f5','75df596f-cfa3-42ce-a335-a3580ce6172b','Aspects of the Moon','aspects-of-the-moon','Moonlit folklore, travelers, spirits and quiet encounters, with full compositions connected to their close-up studies.','World 019',19)
on conflict (id) do nothing;

insert into public.artworks (id,collection_id,title,src,thumb_src,media_type,mood,tags,sort_order)
values ('f364b74b-0b3c-5dc2-88bd-5a5863308a00','8ef7fee8-f4a8-54c1-b91a-9be2d32184f5','Moon Companions','/art/moon-001.webp','/thumbs/moon-001.webp','image','Moonlit folklore and character studies',array['aspects-of-the-moon','moonlight','folklore','character-study','ai-art','moon-study-moon-companions','full-composition' ]::text[],1)
on conflict (id) do nothing;
insert into public.artworks (id,collection_id,title,src,thumb_src,media_type,mood,tags,sort_order)
values ('a04ed5c3-7fb9-5a90-ba51-432560d80754','8ef7fee8-f4a8-54c1-b91a-9be2d32184f5','Moon Companions — Monkey portrait','/art/moon-002.webp','/thumbs/moon-002.webp','image','Moonlit folklore and character studies',array['aspects-of-the-moon','moonlight','folklore','character-study','ai-art','moon-study-moon-companions','detail-study' ]::text[],2)
on conflict (id) do nothing;
insert into public.artworks (id,collection_id,title,src,thumb_src,media_type,mood,tags,sort_order)
values ('8c061c5d-269a-520d-93dd-895dcee36c8f','8ef7fee8-f4a8-54c1-b91a-9be2d32184f5','Moon Companions — Rabbit portrait','/art/moon-003.webp','/thumbs/moon-003.webp','image','Moonlit folklore and character studies',array['aspects-of-the-moon','moonlight','folklore','character-study','ai-art','moon-study-moon-companions','detail-study' ]::text[],3)
on conflict (id) do nothing;
insert into public.artworks (id,collection_id,title,src,thumb_src,media_type,mood,tags,sort_order)
values ('207d1fd9-e379-5d87-a197-975e9f7ab2cc','8ef7fee8-f4a8-54c1-b91a-9be2d32184f5','Moon Companions — Companion diptych','/art/moon-004.webp','/thumbs/moon-004.webp','image','Moonlit folklore and character studies',array['aspects-of-the-moon','moonlight','folklore','character-study','ai-art','moon-study-moon-companions','detail-study' ]::text[],4)
on conflict (id) do nothing;
insert into public.artworks (id,collection_id,title,src,thumb_src,media_type,mood,tags,sort_order)
values ('f7e66140-688c-59e9-b077-ddf75067fda3','8ef7fee8-f4a8-54c1-b91a-9be2d32184f5','Smoke over the Balcony','/art/moon-005.webp','/thumbs/moon-005.webp','image','Moonlit folklore and character studies',array['aspects-of-the-moon','moonlight','folklore','character-study','ai-art','moon-study-balcony-smoke','full-composition' ]::text[],5)
on conflict (id) do nothing;
insert into public.artworks (id,collection_id,title,src,thumb_src,media_type,mood,tags,sort_order)
values ('05a251e2-83a1-55af-acf0-dcb7087eb701','8ef7fee8-f4a8-54c1-b91a-9be2d32184f5','Smoke over the Balcony — Portrait detail','/art/moon-006.webp','/thumbs/moon-006.webp','image','Moonlit folklore and character studies',array['aspects-of-the-moon','moonlight','folklore','character-study','ai-art','moon-study-balcony-smoke','detail-study' ]::text[],6)
on conflict (id) do nothing;
insert into public.artworks (id,collection_id,title,src,thumb_src,media_type,mood,tags,sort_order)
values ('d08aa897-87d0-58b2-a59a-cd9536c72ebb','8ef7fee8-f4a8-54c1-b91a-9be2d32184f5','Flight over the Water','/art/moon-007.webp','/thumbs/moon-007.webp','image','Moonlit folklore and character studies',array['aspects-of-the-moon','moonlight','folklore','character-study','ai-art','moon-study-flight-over-water','full-composition' ]::text[],7)
on conflict (id) do nothing;
insert into public.artworks (id,collection_id,title,src,thumb_src,media_type,mood,tags,sort_order)
values ('60490dfb-28f7-538d-b9a5-e921672a18bd','8ef7fee8-f4a8-54c1-b91a-9be2d32184f5','Flight over the Water — Portrait detail','/art/moon-008.webp','/thumbs/moon-008.webp','image','Moonlit folklore and character studies',array['aspects-of-the-moon','moonlight','folklore','character-study','ai-art','moon-study-flight-over-water','detail-study' ]::text[],8)
on conflict (id) do nothing;
insert into public.artworks (id,collection_id,title,src,thumb_src,media_type,mood,tags,sort_order)
values ('a40b730a-ec5c-5235-8798-989573be5212','8ef7fee8-f4a8-54c1-b91a-9be2d32184f5','Crescent Fox','/art/moon-009.webp','/thumbs/moon-009.webp','image','Moonlit folklore and character studies',array['aspects-of-the-moon','moonlight','folklore','character-study','ai-art','moon-study-crescent-fox','full-composition' ]::text[],9)
on conflict (id) do nothing;
insert into public.artworks (id,collection_id,title,src,thumb_src,media_type,mood,tags,sort_order)
values ('dedd53f0-fb25-5a1b-aa75-f8501d751cdb','8ef7fee8-f4a8-54c1-b91a-9be2d32184f5','Crescent Fox — Portrait detail','/art/moon-010.webp','/thumbs/moon-010.webp','image','Moonlit folklore and character studies',array['aspects-of-the-moon','moonlight','folklore','character-study','ai-art','moon-study-crescent-fox','detail-study' ]::text[],10)
on conflict (id) do nothing;
insert into public.artworks (id,collection_id,title,src,thumb_src,media_type,mood,tags,sort_order)
values ('ac6aca54-81fd-5e57-8443-39665980d849','8ef7fee8-f4a8-54c1-b91a-9be2d32184f5','Blossom Moon','/art/moon-011.webp','/thumbs/moon-011.webp','image','Moonlit folklore and character studies',array['aspects-of-the-moon','moonlight','folklore','character-study','ai-art','moon-study-blossom-moon','full-composition' ]::text[],11)
on conflict (id) do nothing;
insert into public.artworks (id,collection_id,title,src,thumb_src,media_type,mood,tags,sort_order)
values ('85872363-2c20-593a-a009-cecfca40b89e','8ef7fee8-f4a8-54c1-b91a-9be2d32184f5','Blossom Moon — Portrait detail','/art/moon-012.webp','/thumbs/moon-012.webp','image','Moonlit folklore and character studies',array['aspects-of-the-moon','moonlight','folklore','character-study','ai-art','moon-study-blossom-moon','detail-study' ]::text[],12)
on conflict (id) do nothing;
insert into public.artworks (id,collection_id,title,src,thumb_src,media_type,mood,tags,sort_order)
values ('2e1d694e-8354-536e-8430-ae165d398113','8ef7fee8-f4a8-54c1-b91a-9be2d32184f5','Moonlit Court','/art/moon-013.webp','/thumbs/moon-013.webp','image','Moonlit folklore and character studies',array['aspects-of-the-moon','moonlight','folklore','character-study','ai-art','moon-study-moonlit-court','full-composition' ]::text[],13)
on conflict (id) do nothing;
insert into public.artworks (id,collection_id,title,src,thumb_src,media_type,mood,tags,sort_order)
values ('1b21960c-ed39-5bf8-a1ca-c15a6ea0b54e','8ef7fee8-f4a8-54c1-b91a-9be2d32184f5','Moonlit Court — Portrait detail','/art/moon-014.webp','/thumbs/moon-014.webp','image','Moonlit folklore and character studies',array['aspects-of-the-moon','moonlight','folklore','character-study','ai-art','moon-study-moonlit-court','detail-study' ]::text[],14)
on conflict (id) do nothing;
insert into public.artworks (id,collection_id,title,src,thumb_src,media_type,mood,tags,sort_order)
values ('8f829cd3-e9fa-5cb2-800f-9977a4f3f9ef','8ef7fee8-f4a8-54c1-b91a-9be2d32184f5','Mountain Flute','/art/moon-015.webp','/thumbs/moon-015.webp','image','Moonlit folklore and character studies',array['aspects-of-the-moon','moonlight','folklore','character-study','ai-art','moon-study-mountain-flute','full-composition' ]::text[],15)
on conflict (id) do nothing;
insert into public.artworks (id,collection_id,title,src,thumb_src,media_type,mood,tags,sort_order)
values ('ad43a35f-cd32-5fa5-8be9-907bd6350ca4','8ef7fee8-f4a8-54c1-b91a-9be2d32184f5','Mountain Flute — Portrait detail','/art/moon-016.webp','/thumbs/moon-016.webp','image','Moonlit folklore and character studies',array['aspects-of-the-moon','moonlight','folklore','character-study','ai-art','moon-study-mountain-flute','detail-study' ]::text[],16)
on conflict (id) do nothing;
insert into public.artworks (id,collection_id,title,src,thumb_src,media_type,mood,tags,sort_order)
values ('7ccbce8b-c135-5540-a37c-e48f7ae8072d','8ef7fee8-f4a8-54c1-b91a-9be2d32184f5','Reed Warrior','/art/moon-017.webp','/thumbs/moon-017.webp','image','Moonlit folklore and character studies',array['aspects-of-the-moon','moonlight','folklore','character-study','ai-art','moon-study-reed-warrior','full-composition' ]::text[],17)
on conflict (id) do nothing;
insert into public.artworks (id,collection_id,title,src,thumb_src,media_type,mood,tags,sort_order)
values ('9c05e408-9726-5f44-91a0-59ed7f127978','8ef7fee8-f4a8-54c1-b91a-9be2d32184f5','Reed Warrior — Portrait detail','/art/moon-018.webp','/thumbs/moon-018.webp','image','Moonlit folklore and character studies',array['aspects-of-the-moon','moonlight','folklore','character-study','ai-art','moon-study-reed-warrior','detail-study' ]::text[],18)
on conflict (id) do nothing;
insert into public.artworks (id,collection_id,title,src,thumb_src,media_type,mood,tags,sort_order)
values ('50863319-4bbf-59d3-9501-2334458ea6ad','8ef7fee8-f4a8-54c1-b91a-9be2d32184f5','Archer and Deer','/art/moon-019.webp','/thumbs/moon-019.webp','image','Moonlit folklore and character studies',array['aspects-of-the-moon','moonlight','folklore','character-study','ai-art','moon-study-archer-and-deer','full-composition' ]::text[],19)
on conflict (id) do nothing;
insert into public.artworks (id,collection_id,title,src,thumb_src,media_type,mood,tags,sort_order)
values ('78da6c49-f908-5e58-838f-402b67443a81','8ef7fee8-f4a8-54c1-b91a-9be2d32184f5','Archer and Deer — Archer and deer detail','/art/moon-020.webp','/thumbs/moon-020.webp','image','Moonlit folklore and character studies',array['aspects-of-the-moon','moonlight','folklore','character-study','ai-art','moon-study-archer-and-deer','detail-study' ]::text[],20)
on conflict (id) do nothing;
insert into public.artworks (id,collection_id,title,src,thumb_src,media_type,mood,tags,sort_order)
values ('3559a2cf-2325-5990-bd19-89a17938fa04','8ef7fee8-f4a8-54c1-b91a-9be2d32184f5','Mountain Reader','/art/moon-021.webp','/thumbs/moon-021.webp','image','Moonlit folklore and character studies',array['aspects-of-the-moon','moonlight','folklore','character-study','ai-art','moon-study-mountain-reader','full-composition' ]::text[],21)
on conflict (id) do nothing;
insert into public.artworks (id,collection_id,title,src,thumb_src,media_type,mood,tags,sort_order)
values ('4d826c9a-fd58-5897-b18d-475e95bb8d71','8ef7fee8-f4a8-54c1-b91a-9be2d32184f5','Mountain Reader — Portrait detail','/art/moon-022.webp','/thumbs/moon-022.webp','image','Moonlit folklore and character studies',array['aspects-of-the-moon','moonlight','folklore','character-study','ai-art','moon-study-mountain-reader','detail-study' ]::text[],22)
on conflict (id) do nothing;
insert into public.artworks (id,collection_id,title,src,thumb_src,media_type,mood,tags,sort_order)
values ('ba708905-672f-50e3-a172-5e2082fa8b4b','8ef7fee8-f4a8-54c1-b91a-9be2d32184f5','Wave Rider','/art/moon-023.webp','/thumbs/moon-023.webp','image','Moonlit folklore and character studies',array['aspects-of-the-moon','moonlight','folklore','character-study','ai-art','moon-study-wave-rider','full-composition' ]::text[],23)
on conflict (id) do nothing;
insert into public.artworks (id,collection_id,title,src,thumb_src,media_type,mood,tags,sort_order)
values ('4d8debac-5311-5734-af5b-287a5142a4c3','8ef7fee8-f4a8-54c1-b91a-9be2d32184f5','Wave Rider — Portrait detail','/art/moon-024.webp','/thumbs/moon-024.webp','image','Moonlit folklore and character studies',array['aspects-of-the-moon','moonlight','folklore','character-study','ai-art','moon-study-wave-rider','detail-study' ]::text[],24)
on conflict (id) do nothing;
insert into public.artworks (id,collection_id,title,src,thumb_src,media_type,mood,tags,sort_order)
values ('e22b4dc6-84a8-5691-923e-b91730f3294d','8ef7fee8-f4a8-54c1-b91a-9be2d32184f5','Eclipse Encounter','/art/moon-025.webp','/thumbs/moon-025.webp','image','Moonlit folklore and character studies',array['aspects-of-the-moon','moonlight','folklore','character-study','ai-art','moon-study-eclipse-encounter','full-composition' ]::text[],25)
on conflict (id) do nothing;
insert into public.artworks (id,collection_id,title,src,thumb_src,media_type,mood,tags,sort_order)
values ('3bad015e-b50e-5534-b731-eba1676eeb8d','8ef7fee8-f4a8-54c1-b91a-9be2d32184f5','Eclipse Encounter — Encounter detail','/art/moon-026.webp','/thumbs/moon-026.webp','image','Moonlit folklore and character studies',array['aspects-of-the-moon','moonlight','folklore','character-study','ai-art','moon-study-eclipse-encounter','detail-study' ]::text[],26)
on conflict (id) do nothing;
insert into public.artworks (id,collection_id,title,src,thumb_src,media_type,mood,tags,sort_order)
values ('803b5349-762c-531f-94c6-e22c02e36667','8ef7fee8-f4a8-54c1-b91a-9be2d32184f5','Pointing to the Moon','/art/moon-027.webp','/thumbs/moon-027.webp','image','Moonlit folklore and character studies',array['aspects-of-the-moon','moonlight','folklore','character-study','ai-art','moon-study-pointing-to-the-moon','full-composition' ]::text[],27)
on conflict (id) do nothing;
insert into public.artworks (id,collection_id,title,src,thumb_src,media_type,mood,tags,sort_order)
values ('1950170d-61fa-53fd-a975-63861c72c32b','8ef7fee8-f4a8-54c1-b91a-9be2d32184f5','Pointing to the Moon — Gesture detail','/art/moon-028.webp','/thumbs/moon-028.webp','image','Moonlit folklore and character studies',array['aspects-of-the-moon','moonlight','folklore','character-study','ai-art','moon-study-pointing-to-the-moon','detail-study' ]::text[],28)
on conflict (id) do nothing;
insert into public.artworks (id,collection_id,title,src,thumb_src,media_type,mood,tags,sort_order)
values ('16998dee-e8cf-552c-ad48-2373c67ee1d3','8ef7fee8-f4a8-54c1-b91a-9be2d32184f5','White Fox','/art/moon-029.webp','/thumbs/moon-029.webp','image','Moonlit folklore and character studies',array['aspects-of-the-moon','moonlight','folklore','character-study','ai-art','moon-study-white-fox','full-composition' ]::text[],29)
on conflict (id) do nothing;
insert into public.artworks (id,collection_id,title,src,thumb_src,media_type,mood,tags,sort_order)
values ('056089e0-96fb-56a1-8bcb-62c2d4c291a2','8ef7fee8-f4a8-54c1-b91a-9be2d32184f5','White Fox — Portrait detail','/art/moon-030.webp','/thumbs/moon-030.webp','image','Moonlit folklore and character studies',array['aspects-of-the-moon','moonlight','folklore','character-study','ai-art','moon-study-white-fox','detail-study' ]::text[],30)
on conflict (id) do nothing;
insert into public.artworks (id,collection_id,title,src,thumb_src,media_type,mood,tags,sort_order)
values ('03537572-e334-54f3-83bf-5160ba1ba7c1','8ef7fee8-f4a8-54c1-b91a-9be2d32184f5','Red-Robed Meditation','/art/moon-031.webp','/thumbs/moon-031.webp','image','Moonlit folklore and character studies',array['aspects-of-the-moon','moonlight','folklore','character-study','ai-art','moon-study-red-robed-meditation','full-composition' ]::text[],31)
on conflict (id) do nothing;
insert into public.artworks (id,collection_id,title,src,thumb_src,media_type,mood,tags,sort_order)
values ('35ad5770-5278-5023-ab87-39dc6ee3ca82','8ef7fee8-f4a8-54c1-b91a-9be2d32184f5','Red-Robed Meditation — Portrait detail','/art/moon-032.webp','/thumbs/moon-032.webp','image','Moonlit folklore and character studies',array['aspects-of-the-moon','moonlight','folklore','character-study','ai-art','moon-study-red-robed-meditation','detail-study' ]::text[],32)
on conflict (id) do nothing;

do $$ begin
  if (select count(*) from public.artworks where collection_id='8ef7fee8-f4a8-54c1-b91a-9be2d32184f5' and id in ('f364b74b-0b3c-5dc2-88bd-5a5863308a00','a04ed5c3-7fb9-5a90-ba51-432560d80754','8c061c5d-269a-520d-93dd-895dcee36c8f','207d1fd9-e379-5d87-a197-975e9f7ab2cc','f7e66140-688c-59e9-b077-ddf75067fda3','05a251e2-83a1-55af-acf0-dcb7087eb701','d08aa897-87d0-58b2-a59a-cd9536c72ebb','60490dfb-28f7-538d-b9a5-e921672a18bd','a40b730a-ec5c-5235-8798-989573be5212','dedd53f0-fb25-5a1b-aa75-f8501d751cdb','ac6aca54-81fd-5e57-8443-39665980d849','85872363-2c20-593a-a009-cecfca40b89e','2e1d694e-8354-536e-8430-ae165d398113','1b21960c-ed39-5bf8-a1ca-c15a6ea0b54e','8f829cd3-e9fa-5cb2-800f-9977a4f3f9ef','ad43a35f-cd32-5fa5-8be9-907bd6350ca4','7ccbce8b-c135-5540-a37c-e48f7ae8072d','9c05e408-9726-5f44-91a0-59ed7f127978','50863319-4bbf-59d3-9501-2334458ea6ad','78da6c49-f908-5e58-838f-402b67443a81','3559a2cf-2325-5990-bd19-89a17938fa04','4d826c9a-fd58-5897-b18d-475e95bb8d71','ba708905-672f-50e3-a172-5e2082fa8b4b','4d8debac-5311-5734-af5b-287a5142a4c3','e22b4dc6-84a8-5691-923e-b91730f3294d','3bad015e-b50e-5534-b731-eba1676eeb8d','803b5349-762c-531f-94c6-e22c02e36667','1950170d-61fa-53fd-a975-63861c72c32b','16998dee-e8cf-552c-ad48-2373c67ee1d3','056089e0-96fb-56a1-8bcb-62c2d4c291a2','03537572-e334-54f3-83bf-5160ba1ba7c1','35ad5770-5278-5023-ab87-39dc6ee3ca82')) <> 32 then raise exception 'Artwork identity collision'; end if;
end $$;

do $$ begin
  if exists(select 1 from public.world_threads where (slug='aspects-of-the-moon-moon-companions' and id<>'529a430c-c274-5986-8e22-6731ae02610e') or (id='529a430c-c274-5986-8e22-6731ae02610e' and owner_id<>'75df596f-cfa3-42ce-a335-a3580ce6172b')) then raise exception 'Thread identity collision'; end if;
  if not exists(select 1 from public.world_threads where id='529a430c-c274-5986-8e22-6731ae02610e') then
    insert into public.world_threads (id,owner_id,title,slug,summary,visibility,allow_forks)
    values ('529a430c-c274-5986-8e22-6731ae02610e','75df596f-cfa3-42ce-a335-a3580ce6172b','Moon Companions — composition & details','aspects-of-the-moon-moon-companions','The monkey and white rabbit share the moonlit scene. Separate portraits and the two-panel companion study keep those subjects together.','public',false);
    insert into public.world_thread_items (thread_id,artwork_id,position,relation_type,note,added_by) values
    ('529a430c-c274-5986-8e22-6731ae02610e','f364b74b-0b3c-5dc2-88bd-5a5863308a00',1,'origin','Full composition. Curated related study in Moon Companions; not an assertion of an exact pixel crop.','75df596f-cfa3-42ce-a335-a3580ce6172b'),
    ('529a430c-c274-5986-8e22-6731ae02610e','a04ed5c3-7fb9-5a90-ba51-432560d80754',2,'composition','Monkey portrait. Curated related study in Moon Companions; not an assertion of an exact pixel crop.','75df596f-cfa3-42ce-a335-a3580ce6172b'),
    ('529a430c-c274-5986-8e22-6731ae02610e','8c061c5d-269a-520d-93dd-895dcee36c8f',3,'composition','Rabbit portrait. Curated related study in Moon Companions; not an assertion of an exact pixel crop.','75df596f-cfa3-42ce-a335-a3580ce6172b'),
    ('529a430c-c274-5986-8e22-6731ae02610e','207d1fd9-e379-5d87-a197-975e9f7ab2cc',4,'composition','Companion diptych. Curated related study in Moon Companions; not an assertion of an exact pixel crop.','75df596f-cfa3-42ce-a335-a3580ce6172b');
  end if;
end $$;
do $$ begin
  if exists(select 1 from public.world_threads where (slug='aspects-of-the-moon-balcony-smoke' and id<>'fda72fac-68b6-53a5-a69e-6237e323e8a5') or (id='fda72fac-68b6-53a5-a69e-6237e323e8a5' and owner_id<>'75df596f-cfa3-42ce-a335-a3580ce6172b')) then raise exception 'Thread identity collision'; end if;
  if not exists(select 1 from public.world_threads where id='fda72fac-68b6-53a5-a69e-6237e323e8a5') then
    insert into public.world_threads (id,owner_id,title,slug,summary,visibility,allow_forks)
    values ('fda72fac-68b6-53a5-a69e-6237e323e8a5','75df596f-cfa3-42ce-a335-a3580ce6172b','Smoke over the Balcony — composition & details','aspects-of-the-moon-balcony-smoke','The orange floral robe, smoking gesture and balcony scene connect this full composition with its portrait study.','public',false);
    insert into public.world_thread_items (thread_id,artwork_id,position,relation_type,note,added_by) values
    ('fda72fac-68b6-53a5-a69e-6237e323e8a5','f7e66140-688c-59e9-b077-ddf75067fda3',1,'origin','Full composition. Curated related study in Smoke over the Balcony; not an assertion of an exact pixel crop.','75df596f-cfa3-42ce-a335-a3580ce6172b'),
    ('fda72fac-68b6-53a5-a69e-6237e323e8a5','05a251e2-83a1-55af-acf0-dcb7087eb701',2,'composition','Portrait detail. Curated related study in Smoke over the Balcony; not an assertion of an exact pixel crop.','75df596f-cfa3-42ce-a335-a3580ce6172b');
  end if;
end $$;
do $$ begin
  if exists(select 1 from public.world_threads where (slug='aspects-of-the-moon-flight-over-water' and id<>'4ce4b037-2133-59ed-a308-56ec85ac317d') or (id='4ce4b037-2133-59ed-a308-56ec85ac317d' and owner_id<>'75df596f-cfa3-42ce-a335-a3580ce6172b')) then raise exception 'Thread identity collision'; end if;
  if not exists(select 1 from public.world_threads where id='4ce4b037-2133-59ed-a308-56ec85ac317d') then
    insert into public.world_threads (id,owner_id,title,slug,summary,visibility,allow_forks)
    values ('4ce4b037-2133-59ed-a308-56ec85ac317d','75df596f-cfa3-42ce-a335-a3580ce6172b','Flight over the Water — composition & details','aspects-of-the-moon-flight-over-water','The airborne figure and distinctive red-and-purple checked garments connect the full scene and close-up.','public',false);
    insert into public.world_thread_items (thread_id,artwork_id,position,relation_type,note,added_by) values
    ('4ce4b037-2133-59ed-a308-56ec85ac317d','d08aa897-87d0-58b2-a59a-cd9536c72ebb',1,'origin','Full composition. Curated related study in Flight over the Water; not an assertion of an exact pixel crop.','75df596f-cfa3-42ce-a335-a3580ce6172b'),
    ('4ce4b037-2133-59ed-a308-56ec85ac317d','60490dfb-28f7-538d-b9a5-e921672a18bd',2,'composition','Portrait detail. Curated related study in Flight over the Water; not an assertion of an exact pixel crop.','75df596f-cfa3-42ce-a335-a3580ce6172b');
  end if;
end $$;
do $$ begin
  if exists(select 1 from public.world_threads where (slug='aspects-of-the-moon-crescent-fox' and id<>'ae9579d1-c845-55e1-9212-f65947b4cd45') or (id='ae9579d1-c845-55e1-9212-f65947b4cd45' and owner_id<>'75df596f-cfa3-42ce-a335-a3580ce6172b')) then raise exception 'Thread identity collision'; end if;
  if not exists(select 1 from public.world_threads where id='ae9579d1-c845-55e1-9212-f65947b4cd45') then
    insert into public.world_threads (id,owner_id,title,slug,summary,visibility,allow_forks)
    values ('ae9579d1-c845-55e1-9212-f65947b4cd45','75df596f-cfa3-42ce-a335-a3580ce6172b','Crescent Fox — composition & details','aspects-of-the-moon-crescent-fox','The orange fox, teal headcloth and pale patterned robe connect the reed-filled scene and portrait.','public',false);
    insert into public.world_thread_items (thread_id,artwork_id,position,relation_type,note,added_by) values
    ('ae9579d1-c845-55e1-9212-f65947b4cd45','a40b730a-ec5c-5235-8798-989573be5212',1,'origin','Full composition. Curated related study in Crescent Fox; not an assertion of an exact pixel crop.','75df596f-cfa3-42ce-a335-a3580ce6172b'),
    ('ae9579d1-c845-55e1-9212-f65947b4cd45','dedd53f0-fb25-5a1b-aa75-f8501d751cdb',2,'composition','Portrait detail. Curated related study in Crescent Fox; not an assertion of an exact pixel crop.','75df596f-cfa3-42ce-a335-a3580ce6172b');
  end if;
end $$;
do $$ begin
  if exists(select 1 from public.world_threads where (slug='aspects-of-the-moon-blossom-moon' and id<>'af4dbeb8-b9ae-5bfd-9177-91fe2555c67e') or (id='af4dbeb8-b9ae-5bfd-9177-91fe2555c67e' and owner_id<>'75df596f-cfa3-42ce-a335-a3580ce6172b')) then raise exception 'Thread identity collision'; end if;
  if not exists(select 1 from public.world_threads where id='af4dbeb8-b9ae-5bfd-9177-91fe2555c67e') then
    insert into public.world_threads (id,owner_id,title,slug,summary,visibility,allow_forks)
    values ('af4dbeb8-b9ae-5bfd-9177-91fe2555c67e','75df596f-cfa3-42ce-a335-a3580ce6172b','Blossom Moon — composition & details','aspects-of-the-moon-blossom-moon','The blue floral robe, indigo headwrap and green fan connect the blossom scene and portrait.','public',false);
    insert into public.world_thread_items (thread_id,artwork_id,position,relation_type,note,added_by) values
    ('af4dbeb8-b9ae-5bfd-9177-91fe2555c67e','ac6aca54-81fd-5e57-8443-39665980d849',1,'origin','Full composition. Curated related study in Blossom Moon; not an assertion of an exact pixel crop.','75df596f-cfa3-42ce-a335-a3580ce6172b'),
    ('af4dbeb8-b9ae-5bfd-9177-91fe2555c67e','85872363-2c20-593a-a009-cecfca40b89e',2,'composition','Portrait detail. Curated related study in Blossom Moon; not an assertion of an exact pixel crop.','75df596f-cfa3-42ce-a335-a3580ce6172b');
  end if;
end $$;
do $$ begin
  if exists(select 1 from public.world_threads where (slug='aspects-of-the-moon-moonlit-court' and id<>'f9de6e44-09cf-5926-a357-a00c744761bd') or (id='f9de6e44-09cf-5926-a357-a00c744761bd' and owner_id<>'75df596f-cfa3-42ce-a335-a3580ce6172b')) then raise exception 'Thread identity collision'; end if;
  if not exists(select 1 from public.world_threads where id='f9de6e44-09cf-5926-a357-a00c744761bd') then
    insert into public.world_threads (id,owner_id,title,slug,summary,visibility,allow_forks)
    values ('f9de6e44-09cf-5926-a357-a00c744761bd','75df596f-cfa3-42ce-a335-a3580ce6172b','Moonlit Court — composition & details','aspects-of-the-moon-moonlit-court','The layered court robes, pinned hair and large full moon connect this scene and portrait study.','public',false);
    insert into public.world_thread_items (thread_id,artwork_id,position,relation_type,note,added_by) values
    ('f9de6e44-09cf-5926-a357-a00c744761bd','2e1d694e-8354-536e-8430-ae165d398113',1,'origin','Full composition. Curated related study in Moonlit Court; not an assertion of an exact pixel crop.','75df596f-cfa3-42ce-a335-a3580ce6172b'),
    ('f9de6e44-09cf-5926-a357-a00c744761bd','1b21960c-ed39-5bf8-a1ca-c15a6ea0b54e',2,'composition','Portrait detail. Curated related study in Moonlit Court; not an assertion of an exact pixel crop.','75df596f-cfa3-42ce-a335-a3580ce6172b');
  end if;
end $$;
do $$ begin
  if exists(select 1 from public.world_threads where (slug='aspects-of-the-moon-mountain-flute' and id<>'856ebbd8-715e-5995-bc14-10a4c400239c') or (id='856ebbd8-715e-5995-bc14-10a4c400239c' and owner_id<>'75df596f-cfa3-42ce-a335-a3580ce6172b')) then raise exception 'Thread identity collision'; end if;
  if not exists(select 1 from public.world_threads where id='856ebbd8-715e-5995-bc14-10a4c400239c') then
    insert into public.world_threads (id,owner_id,title,slug,summary,visibility,allow_forks)
    values ('856ebbd8-715e-5995-bc14-10a4c400239c','75df596f-cfa3-42ce-a335-a3580ce6172b','Mountain Flute — composition & details','aspects-of-the-moon-mountain-flute','The bearded flute player, pale robes and dark headpiece connect the mountain scene and close-up.','public',false);
    insert into public.world_thread_items (thread_id,artwork_id,position,relation_type,note,added_by) values
    ('856ebbd8-715e-5995-bc14-10a4c400239c','8f829cd3-e9fa-5cb2-800f-9977a4f3f9ef',1,'origin','Full composition. Curated related study in Mountain Flute; not an assertion of an exact pixel crop.','75df596f-cfa3-42ce-a335-a3580ce6172b'),
    ('856ebbd8-715e-5995-bc14-10a4c400239c','ad43a35f-cd32-5fa5-8be9-907bd6350ca4',2,'composition','Portrait detail. Curated related study in Mountain Flute; not an assertion of an exact pixel crop.','75df596f-cfa3-42ce-a335-a3580ce6172b');
  end if;
end $$;
do $$ begin
  if exists(select 1 from public.world_threads where (slug='aspects-of-the-moon-reed-warrior' and id<>'cf018bbb-86ae-5199-b3d1-60ea8eef7fae') or (id='cf018bbb-86ae-5199-b3d1-60ea8eef7fae' and owner_id<>'75df596f-cfa3-42ce-a335-a3580ce6172b')) then raise exception 'Thread identity collision'; end if;
  if not exists(select 1 from public.world_threads where id='cf018bbb-86ae-5199-b3d1-60ea8eef7fae') then
    insert into public.world_threads (id,owner_id,title,slug,summary,visibility,allow_forks)
    values ('cf018bbb-86ae-5199-b3d1-60ea8eef7fae','75df596f-cfa3-42ce-a335-a3580ce6172b','Reed Warrior — composition & details','aspects-of-the-moon-reed-warrior','The warrior''s striped sleeves and back-mounted equipment connect the reed scene and portrait.','public',false);
    insert into public.world_thread_items (thread_id,artwork_id,position,relation_type,note,added_by) values
    ('cf018bbb-86ae-5199-b3d1-60ea8eef7fae','7ccbce8b-c135-5540-a37c-e48f7ae8072d',1,'origin','Full composition. Curated related study in Reed Warrior; not an assertion of an exact pixel crop.','75df596f-cfa3-42ce-a335-a3580ce6172b'),
    ('cf018bbb-86ae-5199-b3d1-60ea8eef7fae','9c05e408-9726-5f44-91a0-59ed7f127978',2,'composition','Portrait detail. Curated related study in Reed Warrior; not an assertion of an exact pixel crop.','75df596f-cfa3-42ce-a335-a3580ce6172b');
  end if;
end $$;
do $$ begin
  if exists(select 1 from public.world_threads where (slug='aspects-of-the-moon-archer-and-deer' and id<>'4eceb6d7-b6c1-55c0-877f-fb1a23ad0b71') or (id='4eceb6d7-b6c1-55c0-877f-fb1a23ad0b71' and owner_id<>'75df596f-cfa3-42ce-a335-a3580ce6172b')) then raise exception 'Thread identity collision'; end if;
  if not exists(select 1 from public.world_threads where id='4eceb6d7-b6c1-55c0-877f-fb1a23ad0b71') then
    insert into public.world_threads (id,owner_id,title,slug,summary,visibility,allow_forks)
    values ('4eceb6d7-b6c1-55c0-877f-fb1a23ad0b71','75df596f-cfa3-42ce-a335-a3580ce6172b','Archer and Deer — composition & details','aspects-of-the-moon-archer-and-deer','The pale-robed archer and deer from the hillside composition reappear together in the split close-up study.','public',false);
    insert into public.world_thread_items (thread_id,artwork_id,position,relation_type,note,added_by) values
    ('4eceb6d7-b6c1-55c0-877f-fb1a23ad0b71','50863319-4bbf-59d3-9501-2334458ea6ad',1,'origin','Full composition. Curated related study in Archer and Deer; not an assertion of an exact pixel crop.','75df596f-cfa3-42ce-a335-a3580ce6172b'),
    ('4eceb6d7-b6c1-55c0-877f-fb1a23ad0b71','78da6c49-f908-5e58-838f-402b67443a81',2,'composition','Archer and deer detail. Curated related study in Archer and Deer; not an assertion of an exact pixel crop.','75df596f-cfa3-42ce-a335-a3580ce6172b');
  end if;
end $$;
do $$ begin
  if exists(select 1 from public.world_threads where (slug='aspects-of-the-moon-mountain-reader' and id<>'6f1b39db-f2b1-5b44-882e-38603a411121') or (id='6f1b39db-f2b1-5b44-882e-38603a411121' and owner_id<>'75df596f-cfa3-42ce-a335-a3580ce6172b')) then raise exception 'Thread identity collision'; end if;
  if not exists(select 1 from public.world_threads where id='6f1b39db-f2b1-5b44-882e-38603a411121') then
    insert into public.world_threads (id,owner_id,title,slug,summary,visibility,allow_forks)
    values ('6f1b39db-f2b1-5b44-882e-38603a411121','75df596f-cfa3-42ce-a335-a3580ce6172b','Mountain Reader — composition & details','aspects-of-the-moon-mountain-reader','The wrapped headcloth, weathered travel clothes and open text connect the mountain scene and reader portrait.','public',false);
    insert into public.world_thread_items (thread_id,artwork_id,position,relation_type,note,added_by) values
    ('6f1b39db-f2b1-5b44-882e-38603a411121','3559a2cf-2325-5990-bd19-89a17938fa04',1,'origin','Full composition. Curated related study in Mountain Reader; not an assertion of an exact pixel crop.','75df596f-cfa3-42ce-a335-a3580ce6172b'),
    ('6f1b39db-f2b1-5b44-882e-38603a411121','4d826c9a-fd58-5897-b18d-475e95bb8d71',2,'composition','Portrait detail. Curated related study in Mountain Reader; not an assertion of an exact pixel crop.','75df596f-cfa3-42ce-a335-a3580ce6172b');
  end if;
end $$;
do $$ begin
  if exists(select 1 from public.world_threads where (slug='aspects-of-the-moon-wave-rider' and id<>'c99b4cb9-8908-562a-ad50-9d1564e6032c') or (id='c99b4cb9-8908-562a-ad50-9d1564e6032c' and owner_id<>'75df596f-cfa3-42ce-a335-a3580ce6172b')) then raise exception 'Thread identity collision'; end if;
  if not exists(select 1 from public.world_threads where id='c99b4cb9-8908-562a-ad50-9d1564e6032c') then
    insert into public.world_threads (id,owner_id,title,slug,summary,visibility,allow_forks)
    values ('c99b4cb9-8908-562a-ad50-9d1564e6032c','75df596f-cfa3-42ce-a335-a3580ce6172b','Wave Rider — composition & details','aspects-of-the-moon-wave-rider','The silver-haired figure, black-and-gold cloak and cresting wave connect the boat scene and close-up.','public',false);
    insert into public.world_thread_items (thread_id,artwork_id,position,relation_type,note,added_by) values
    ('c99b4cb9-8908-562a-ad50-9d1564e6032c','ba708905-672f-50e3-a172-5e2082fa8b4b',1,'origin','Full composition. Curated related study in Wave Rider; not an assertion of an exact pixel crop.','75df596f-cfa3-42ce-a335-a3580ce6172b'),
    ('c99b4cb9-8908-562a-ad50-9d1564e6032c','4d8debac-5311-5734-af5b-287a5142a4c3',2,'composition','Portrait detail. Curated related study in Wave Rider; not an assertion of an exact pixel crop.','75df596f-cfa3-42ce-a335-a3580ce6172b');
  end if;
end $$;
do $$ begin
  if exists(select 1 from public.world_threads where (slug='aspects-of-the-moon-eclipse-encounter' and id<>'cc1aeb0a-c226-5f7e-b595-bd4aa1bf6eb7') or (id='cc1aeb0a-c226-5f7e-b595-bd4aa1bf6eb7' and owner_id<>'75df596f-cfa3-42ce-a335-a3580ce6172b')) then raise exception 'Thread identity collision'; end if;
  if not exists(select 1 from public.world_threads where id='cc1aeb0a-c226-5f7e-b595-bd4aa1bf6eb7') then
    insert into public.world_threads (id,owner_id,title,slug,summary,visibility,allow_forks)
    values ('cc1aeb0a-c226-5f7e-b595-bd4aa1bf6eb7','75df596f-cfa3-42ce-a335-a3580ce6172b','Eclipse Encounter — composition & details','aspects-of-the-moon-eclipse-encounter','The red-robed woman and winged figure beneath an eclipse connect the full encounter and face-to-face detail.','public',false);
    insert into public.world_thread_items (thread_id,artwork_id,position,relation_type,note,added_by) values
    ('cc1aeb0a-c226-5f7e-b595-bd4aa1bf6eb7','e22b4dc6-84a8-5691-923e-b91730f3294d',1,'origin','Full composition. Curated related study in Eclipse Encounter; not an assertion of an exact pixel crop.','75df596f-cfa3-42ce-a335-a3580ce6172b'),
    ('cc1aeb0a-c226-5f7e-b595-bd4aa1bf6eb7','3bad015e-b50e-5534-b731-eba1676eeb8d',2,'composition','Encounter detail. Curated related study in Eclipse Encounter; not an assertion of an exact pixel crop.','75df596f-cfa3-42ce-a335-a3580ce6172b');
  end if;
end $$;
do $$ begin
  if exists(select 1 from public.world_threads where (slug='aspects-of-the-moon-pointing-to-the-moon' and id<>'16861554-48e6-5397-97b3-9277fec9b222') or (id='16861554-48e6-5397-97b3-9277fec9b222' and owner_id<>'75df596f-cfa3-42ce-a335-a3580ce6172b')) then raise exception 'Thread identity collision'; end if;
  if not exists(select 1 from public.world_threads where id='16861554-48e6-5397-97b3-9277fec9b222') then
    insert into public.world_threads (id,owner_id,title,slug,summary,visibility,allow_forks)
    values ('16861554-48e6-5397-97b3-9277fec9b222','75df596f-cfa3-42ce-a335-a3580ce6172b','Pointing to the Moon — composition & details','aspects-of-the-moon-pointing-to-the-moon','The green-robed traveler and raised finger connect the wide composition and gesture close-up.','public',false);
    insert into public.world_thread_items (thread_id,artwork_id,position,relation_type,note,added_by) values
    ('16861554-48e6-5397-97b3-9277fec9b222','803b5349-762c-531f-94c6-e22c02e36667',1,'origin','Full composition. Curated related study in Pointing to the Moon; not an assertion of an exact pixel crop.','75df596f-cfa3-42ce-a335-a3580ce6172b'),
    ('16861554-48e6-5397-97b3-9277fec9b222','1950170d-61fa-53fd-a975-63861c72c32b',2,'composition','Gesture detail. Curated related study in Pointing to the Moon; not an assertion of an exact pixel crop.','75df596f-cfa3-42ce-a335-a3580ce6172b');
  end if;
end $$;
do $$ begin
  if exists(select 1 from public.world_threads where (slug='aspects-of-the-moon-white-fox' and id<>'115e5afb-68cc-5994-ac70-f73e2039c90d') or (id='115e5afb-68cc-5994-ac70-f73e2039c90d' and owner_id<>'75df596f-cfa3-42ce-a335-a3580ce6172b')) then raise exception 'Thread identity collision'; end if;
  if not exists(select 1 from public.world_threads where id='115e5afb-68cc-5994-ac70-f73e2039c90d') then
    insert into public.world_threads (id,owner_id,title,slug,summary,visibility,allow_forks)
    values ('115e5afb-68cc-5994-ac70-f73e2039c90d','75df596f-cfa3-42ce-a335-a3580ce6172b','White Fox — composition & details','aspects-of-the-moon-white-fox','The white fox, gold pendant and moonlit reeds connect the full animal study and frontal portrait.','public',false);
    insert into public.world_thread_items (thread_id,artwork_id,position,relation_type,note,added_by) values
    ('115e5afb-68cc-5994-ac70-f73e2039c90d','16998dee-e8cf-552c-ad48-2373c67ee1d3',1,'origin','Full composition. Curated related study in White Fox; not an assertion of an exact pixel crop.','75df596f-cfa3-42ce-a335-a3580ce6172b'),
    ('115e5afb-68cc-5994-ac70-f73e2039c90d','056089e0-96fb-56a1-8bcb-62c2d4c291a2',2,'composition','Portrait detail. Curated related study in White Fox; not an assertion of an exact pixel crop.','75df596f-cfa3-42ce-a335-a3580ce6172b');
  end if;
end $$;
do $$ begin
  if exists(select 1 from public.world_threads where (slug='aspects-of-the-moon-red-robed-meditation' and id<>'191631d8-fb55-585e-90a1-f2fa5e2ef298') or (id='191631d8-fb55-585e-90a1-f2fa5e2ef298' and owner_id<>'75df596f-cfa3-42ce-a335-a3580ce6172b')) then raise exception 'Thread identity collision'; end if;
  if not exists(select 1 from public.world_threads where id='191631d8-fb55-585e-90a1-f2fa5e2ef298') then
    insert into public.world_threads (id,owner_id,title,slug,summary,visibility,allow_forks)
    values ('191631d8-fb55-585e-90a1-f2fa5e2ef298','75df596f-cfa3-42ce-a335-a3580ce6172b','Red-Robed Meditation — composition & details','aspects-of-the-moon-red-robed-meditation','The bearded figure''s red hood and robe connect the seated woodland scene and close-up.','public',false);
    insert into public.world_thread_items (thread_id,artwork_id,position,relation_type,note,added_by) values
    ('191631d8-fb55-585e-90a1-f2fa5e2ef298','03537572-e334-54f3-83bf-5160ba1ba7c1',1,'origin','Full composition. Curated related study in Red-Robed Meditation; not an assertion of an exact pixel crop.','75df596f-cfa3-42ce-a335-a3580ce6172b'),
    ('191631d8-fb55-585e-90a1-f2fa5e2ef298','35ad5770-5278-5023-ab87-39dc6ee3ca82',2,'composition','Portrait detail. Curated related study in Red-Robed Meditation; not an assertion of an exact pixel crop.','75df596f-cfa3-42ce-a335-a3580ce6172b');
  end if;
end $$;
set constraints all immediate;
commit;
